Small but significant changes
DanielTheCUPMaker/Tracer pull request #81
Opened 2019-12-23 12:22 UTC by LousyDuck

2019-12-23 16:43 UTC, tomtzook requested changes
Thingy

2019-12-23 16:43 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/MotionControllerParameters.java
> +    public static MotionControllerParameters theoreticalParameters(MotionParameters max, double maxVoltage, double kS) {
Bellow ctor..

2019-12-23 16:43 UTC, tomtzook commented on tracerj/src/main/java/calculus/segments/SegmentSequence.java
> +public class SegmentSequence<S extends Segment> implements Segment {
You implement `Segment` without generic parameters... You should always specify

2019-12-23 16:43 UTC, tomtzook commented on tracerj/src/main/java/calculus/segments/Segment.java
> +    T get();
remove this

2019-12-23 16:43 UTC, tomtzook commented on tracerj/src/main/java/calculus/splines/Spline.java
> +    public double start() {
Missing `@Override`

2019-12-23 16:43 UTC, tomtzook commented on tracerj/src/main/java/calculus/segments/SegmentSequence.java
> +    private final List<S> segments;
You might find `Deque` more comfortable for `start` `end`

2019-12-25 17:18 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/MotionControllerParameters.java
> +    public static MotionControllerParameters theoreticalParameters(MotionParameters max, double maxVoltage, double kS) {
removed

2019-12-25 17:20 UTC, LousyDuck commented on tracerj/src/main/java/calculus/segments/SegmentSequence.java
> +public class SegmentSequence<S extends Segment> implements Segment {
removed parameter from Segment altogether since there is no get, so no need for a type.

2019-12-25 17:20 UTC, LousyDuck commented on tracerj/src/main/java/calculus/segments/Segment.java
> +    T get();
removed

2019-12-25 17:20 UTC, LousyDuck commented on tracerj/src/main/java/calculus/splines/Spline.java
> +    public double start() {
added

2019-12-30 01:04 UTC, tomtzook requested changes
Finishing touches required

2019-12-30 01:04 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TankTrajectoryController.java
> +        try {
hMMMMM It's supposed to be a temporary solution...

2019-12-30 01:04 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +        return  - currentAngle;
Intentional?

2019-12-30 01:04 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/parameters/MotionControllerParameters.java
> +    private final double kV;
Document the meaning of those parameters

2019-12-30 01:04 UTC, tomtzook commented on tracerj/src/main/java/tracer/trajectories/SwerveTrajectory.java
> +                .map(waypoint -> shiftForX(shiftForY(waypoint, yOffset), xOffset))
Hmmm, _shiftX_ is based on a modified waypoint?

2019-12-30 01:04 UTC, tomtzook commented on tracerj/src/test/java/Main.java
> +import calculus.splines.SplineType;
This shouldn't really exist. Instead use actual tests

2019-12-30 19:59 UTC, LousyDuck commented on build.gradle
> +        compile "com.flash3388.flashlib:flashlib:2.0.0-beta.7"
sure

2019-12-30 19:59 UTC, LousyDuck commented on tracerj/src/main/java/calculus/functions/ParametricFunction.java
>      public PolynomialFunction tFunction() {
oopsy

2019-12-30 20:00 UTC, LousyDuck commented on tracerj/src/main/java/calculus/splines/Spline.java
> +        return ExtendedMath.equals(xFunctionDerivative.applyAsDouble(0), other.xFunctionDerivative.applyAsDouble(0), ACCURACY) &&
me too, will fix

2019-12-30 20:02 UTC, LousyDuck commented on tracerj/src/main/java/calculus/splines/parameters/Waypoint.java
> +    public static Waypoint point(double x, double y) {
removed

2019-12-30 20:36 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TankTrajectoryController.java
> +        try {
fixed, but not sure if it's right

2019-12-30 20:36 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TankTrajectoryController.java
> +        try {
I mean proper

2019-12-30 20:37 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +        return  - currentAngle;
removed it

2019-12-30 20:37 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/parameters/MotionControllerParameters.java
> +    private final double kV;
you mean in java docs?

2019-12-30 20:38 UTC, LousyDuck commented on tracerj/src/main/java/tracer/trajectories/SwerveTrajectory.java
> +                .map(waypoint -> shiftForX(shiftForY(waypoint, yOffset), xOffset))
yup, I don't change the angle so it's alright

2019-12-30 20:38 UTC, LousyDuck commented on tracerj/src/test/java/Main.java
> +import calculus.splines.SplineType;
yeah, just checked if stuff works

2019-12-30 20:39 UTC, LousyDuck commented
so... You don't close pull requests now?

2019-12-31 01:17 UTC, tomtzook requested changes
- FIX THE TESTS
- Did you work on backwards trajectory?

2019-12-31 01:17 UTC, tomtzook commented on tracerj/src/main/java/calculus/splines/Spline.java
> +        return ExtendedMath.equals(xFunctionDerivative.applyAsDouble(0), other.xFunctionDerivative.applyAsDouble(0), ACCURACY) &&
Only you didn't?

2019-12-31 01:17 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/ProfileMotionController.java
> +    private final double kS;
Why not just store `MotionControllerParameters`?

2019-12-31 01:17 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TrajectoryController.java
>          return trajectoryProfile.finalTimestamp();
well assuming start timestamp is _0_

2019-12-31 01:17 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +        } catch (IllegalArgumentException ignored) {
hmmm?

2019-12-31 01:17 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/parameters/MotionControllerParameters.java
> +    private final double kV;
Sure

2019-12-31 01:17 UTC, tomtzook commented on tracerj/src/main/java/tracer/trajectories/SwerveTrajectory.java
>      public SwerveTrajectory(SplineType splineType, List<Waypoint> centerPath, double widthDistanceMeters, double lengthDistanceMeters) {
Why not just remove Swerve for now? There's enough work already

2019-12-31 02:38 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/parameters/MotionControllerParameters.java
> +    private final double kV;
so a different branch then?

2019-12-31 02:38 UTC, LousyDuck commented on tracerj/src/main/java/calculus/splines/Spline.java
> +        return ExtendedMath.equals(xFunctionDerivative.applyAsDouble(0), other.xFunctionDerivative.applyAsDouble(0), ACCURACY) &&
ah frick, on it

2019-12-31 02:42 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/ProfileMotionController.java
> +    private final double kS;
thought it would be clearer, but ok

2019-12-31 02:45 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryController.java
>          return trajectoryProfile.finalTimestamp();
fixed

2019-12-31 02:46 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +        } catch (IllegalArgumentException ignored) {
dude I can't really change the trajectory but it won't be right to do it there either

2019-12-31 02:47 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +        } catch (IllegalArgumentException ignored) {
also, "hmmm" is not a comment

2019-12-31 02:47 UTC, LousyDuck commented on tracerj/src/main/java/tracer/trajectories/SwerveTrajectory.java
>      public SwerveTrajectory(SplineType splineType, List<Waypoint> centerPath, double widthDistanceMeters, double lengthDistanceMeters) {
;-;

2019-12-31 02:48 UTC, LousyDuck commented on tracerj/src/main/java/tracer/trajectories/SwerveTrajectory.java
>      public SwerveTrajectory(SplineType splineType, List<Waypoint> centerPath, double widthDistanceMeters, double lengthDistanceMeters) {
removed

2019-12-31 06:51 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/parameters/MotionControllerParameters.java
> +    private final double kV;
nope

2019-12-31 12:15 UTC, LousyDuck commented
fixed tests

2019-12-31 18:08 UTC, tomtzook requested changes
Nice, just some finishing touches

2019-12-31 18:08 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TankTrajectoryController.java
> +        if(trajectory.right().end() > trajectory.left().end()) {
Did you check it?

2019-12-31 18:08 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +        } catch (IllegalArgumentException ignored) {
Catching an unchecked exception, especially `IllegalArgumentException` is bad. You can replace it with an `if` check on `passedDistance` and `.end()`.

2019-12-31 18:08 UTC, tomtzook commented on tracerj/src/test/java/calculus/splines/HermiteCubicSplineTest.java
>      public void createInstance_ofLineSpline_returnsCorrectSpline() {
I don't understand this test..

2019-12-31 18:08 UTC, tomtzook commented on tracerj/src/test/java/calculus/splines/SplineTest.java
>      public void arcLength_ofLineSpline_returnsCorrectArcLength() {
You may want to do a parametric test for this, and test multiple parameters. Generally in math logic it's best to use parametric tests, to test multiple inputs. However, the parametric test in `junit4` is rather terrible so I would suggest using `junit5`.

2020-01-14 00:51 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +        } catch (IllegalArgumentException ignored) {
done in a similiar way

2020-01-14 01:00 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/parameters/MotionControllerParameters.java
> +    private final double kV;
done

2020-01-14 01:05 UTC, LousyDuck commented on tracerj/src/main/java/calculus/segments/SegmentSequence.java
> +        for (S segment: segments)
it makes sense, though in my use cases it's irrelevant since they're ought to be pretty short... May add later

2020-01-14 01:06 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TankTrajectoryController.java
> +        if(trajectory.right().end() > trajectory.left().end()) {
No. But I did create a test for it and so far so good

2020-01-14 01:06 UTC, LousyDuck commented on tracerj/src/test/java/calculus/splines/HermiteCubicSplineTest.java
>      public void createInstance_ofLineSpline_returnsCorrectSpline() {
changed now, hopefully clearer

2020-01-14 01:07 UTC, LousyDuck commented on tracerj/src/test/java/calculus/splines/SplineTest.java
>      public void arcLength_ofLineSpline_returnsCorrectArcLength() {
done

2020-01-15 18:54 UTC, LousyDuck commented
stopped adding or changing features (may be except adding tests) so it's good for CRing

2020-01-21 17:50 UTC, tomtzook requested changes
Start with a few changes. Then prove to me it actually works.

2020-01-21 17:50 UTC, tomtzook commented on local.properties
> +sdk.dir=/home/daniel/Android/Sdk
was ist loss?!

2020-01-21 17:50 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +    private double shortestAngularDistance(double from, double to) {
Extract as a utility to some other class, and add tests...

2020-01-21 17:50 UTC, tomtzook commented on tracerj/src/test/java/calculus/VariableTest.java
>      public void addition_forVariablesWithDifferentPowers_ThrowsException() {
Test name should be: "{name_of_method}_{current_condition}_{expected_result}". _addition_ is not the method...

In addition each part should also be camal case.

So fix the cases and naming across all tests.

2020-01-21 17:50 UTC, tomtzook commented on tracerj/src/test/java/calculus/splines/HermiteCubicSplineTest.java
> +        assertEquals(actual, expected);
Using _assertThat_ from _Hamcrest_ library is way better than _assertEquals_. Recommend switching to it.

2020-01-21 18:38 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/factories/TrajectoryOrientationControllerFactory.java
> +    public TrajectoryOrientationController create(Trajectory trajectory, Profile trajectoryProfile, boolean isForward) {
Replace `isForward` with `Direction`, its way more clear for users.

2020-01-21 20:24 UTC, tomtzook commented on tracerj/build.gradle
For sources and javadoc, add
```Java
task sourcesJar(type: Jar, dependsOn: classes) {
    archiveBaseName.set(project.name)
    archiveClassifier.set('sources')

    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveBaseName.set(project.name)
    archiveClassifier.set('javadoc')

    from javadoc.destinationDir
}
```

2020-01-21 20:25 UTC, tomtzook commented on tracerj/build.gradle
> +            from components.java
For sources and javadoc, after tasks
```Java
artifact sourcesJar
artifact javadocJar
```

2020-01-23 03:43 UTC, LousyDuck commented on local.properties
> +sdk.dir=/home/daniel/Android/Sdk
deleted

2020-01-23 03:45 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +    private double shortestAngularDistance(double from, double to) {
what tests?

2020-01-23 03:52 UTC, LousyDuck commented on tracerj/src/test/java/calculus/VariableTest.java
>      public void addition_forVariablesWithDifferentPowers_ThrowsException() {
I think I fixed it

2020-01-23 03:58 UTC, LousyDuck commented on tracerj/src/test/java/calculus/splines/HermiteCubicSplineTest.java
> +        assertEquals(actual, expected);
how is it different? and is it necessary enough to add a dependency? I though it just calls the equals method...

2020-01-23 03:59 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/factories/TrajectoryOrientationControllerFactory.java
> +    public TrajectoryOrientationController create(Trajectory trajectory, Profile trajectoryProfile, boolean isForward) {
if it's direction then which value is forward? probably true is forward but it's less clear if anything

2020-01-23 04:00 UTC, LousyDuck commented on tracerj/build.gradle
I also need to call the tasks from somewhere right?

2020-01-23 04:01 UTC, LousyDuck commented on tracerj/build.gradle
> +            from components.java
yeah makes sense

2020-01-23 04:04 UTC, LousyDuck commented
looks like I fixed at least some of the issues that were found on the previous test

2020-01-24 00:23 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/factories/TrajectoryOrientationControllerFactory.java
> +    public TrajectoryOrientationController create(Trajectory trajectory, Profile trajectoryProfile, boolean isForward) {
I meant change the type.

2020-01-24 00:24 UTC, tomtzook commented on tracerj/src/test/java/calculus/splines/HermiteCubicSplineTest.java
> +        assertEquals(actual, expected);
_Hamcrest_ provides a powerful and more clear way to assert. I recommend it, but I won't force it.

2020-01-24 00:24 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +    private double shortestAngularDistance(double from, double to) {
To test that this method works...

2020-01-24 00:44 UTC, tomtzook requested changes

2020-01-24 00:44 UTC, tomtzook commented on tracerj/build.gradle
> +apply plugin: 'maven-publish'
Try using the new plugins _DSL_ format:
```Groovy
plugins {
    id 'maven-publish'
}
```

2020-01-24 00:44 UTC, tomtzook commented on tracerj/build.gradle
> +//task javadocJar(type: Jar, dependsOn: javadoc) {
hmmm either keep the task, or delete the comments.

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/main/java/tracer/actions/TankTrajectoryFollowerAction.java
> +        System.out.println(relativeTime.valueAsMillis()/1000.0);
yeahh... no...

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/main/java/tracer/motion/MotionState.java
> +    private final static double DEF_DELTA = 0.001;
full names plox

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/main/java/tracer/motion/MotionState.java
> +    public static MotionState stop() {
More like "not moving"

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/ProfileMotionController.java
> +        double velocity = profile.state(position.timestamp()).velocity();
The all concept of _snapshot_ is to use the same snapshot. So save the state into a local variable and access it, don't call it twice.

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/TrajectoryController.java
> +        double pidOut = pidController.calculate(position);
All of these controllers use the same profile's state. Again, this violates the snapshot paradigm. Read the state prior, and pass it to the different controllers in `calculate`.

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/main/java/tracer/profiles/MoreBasicProfile.java
> +public abstract class MoreBasicProfile implements Profile {
More like `ProfileBase`, or `AbstractProfile`.

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/main/java/tracer/profiles/ProfileDelegate.java
> +public class ProfileDelegate extends MoreBasicProfile {
`DelegatedProfile` you mean

2020-01-24 00:44 UTC, tomtzook commented on tracerj/src/test/java/calculus/VariableTest.java
> +    public void multiplication_forTwoVariables_returnsAddedSquaresAndMultipliedModifiers() {
The method tested is called `mul`, so the test method will start with `mul_`

2020-01-24 18:32 UTC, LousyDuck commented on tracerj/src/main/java/tracer/motion/MotionState.java
> +    private final static double DEF_DELTA = 0.001;
ok

2020-01-24 18:32 UTC, LousyDuck commented on tracerj/src/main/java/tracer/actions/TankTrajectoryFollowerAction.java
> +        System.out.println(relativeTime.valueAsMillis()/1000.0);
I did an oopsy

2020-01-24 18:33 UTC, LousyDuck commented on tracerj/build.gradle
> +//task javadocJar(type: Jar, dependsOn: javadoc) {
;-;

2020-01-24 18:33 UTC, LousyDuck commented on tracerj/build.gradle
> +apply plugin: 'maven-publish'
ok

2020-01-24 18:34 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/factories/TrajectoryOrientationControllerFactory.java
> +    public TrajectoryOrientationController create(Trajectory trajectory, Profile trajectoryProfile, boolean isForward) {
oh, it's a thing? cool

2020-01-24 18:38 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryOrientationController.java
> +    private double shortestAngularDistance(double from, double to) {
I don't like tests ;-;

2020-01-24 18:39 UTC, LousyDuck commented on tracerj/src/main/java/tracer/motion/MotionState.java
> +    public static MotionState stop() {
so none? or no movement

2020-01-24 18:42 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/ProfileMotionController.java
> +        double velocity = profile.state(position.timestamp()).velocity();
did you mean the 'whole' concept?

2020-01-24 18:44 UTC, LousyDuck commented on tracerj/src/main/java/tracer/controllers/TrajectoryController.java
> +        double pidOut = pidController.calculate(position);
dude? the position remains the same, therefore the state will also be the same. No need to pass it.

2020-01-24 18:45 UTC, LousyDuck commented on tracerj/src/main/java/tracer/profiles/MoreBasicProfile.java
> +public abstract class MoreBasicProfile implements Profile {
yeah, base (abstract is meaningless, even more then base)

2020-01-24 18:46 UTC, LousyDuck commented on tracerj/src/main/java/tracer/profiles/ProfileDelegate.java
> +public class ProfileDelegate extends MoreBasicProfile {
yup

2020-01-24 18:49 UTC, LousyDuck commented on tracerj/src/test/java/calculus/VariableTest.java
> +    public void multiplication_forTwoVariables_returnsAddedSquaresAndMultipliedModifiers() {
makes sense

2021-01-15 11:02 UTC, merged

2021-01-15 11:03 UTC, tomtzook commented
NOT APPROVED BUT MERGED DUE TO PEER PRESSURE

2023-12-30 13:47 UTC, tomtzook reviewed
The code is pretty good, only some minor issues.
Please next time make sure your lines aren't too long as it makes it harder to read.

2023-12-30 13:47 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/factories/TankTrajectoryControllerFactory.java
> +            left = extendProfile(left, calcIdleTime(right, left, true));
This code is problematic, you need to check the `y` value first to see that it is valid, and only then can you compare to `x`.

2023-12-30 13:47 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/factories/TankTrajectoryControllerFactory.java
> +        return isRightLonger ? right.deltaState().timestamp().sub(left.deltaState().timestamp()) : left.deltaState().timestamp().sub(right.deltaState().timestamp());
For ternary operators: organize the code, by using line breaks, after `?` and after `:`, example:

```
a = condition ?
    stateA :
    stateB;
```

2023-12-30 13:48 UTC, tomtzook commented on tracerj/src/main/java/tracer/controllers/factories/TankTrajectoryControllerFactory.java
> +            left = extendProfile(left, calcIdleTime(right, left, true));
Actually, in this flow, the `y` value is always valid because......